# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20170124_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='components',
            old_name='user_name',
            new_name='user',
        ),
    ]
